backend:
  name: github
  repo: drake-zerep/ccooprosegurtenerife
  branch: main

media_folder: "img/noticias"
public_folder: "/img/noticias"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Categoría", name: "category", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Contenido", name: "body", widget: "markdown"}
